[package]
name = "hermes"
version = "0.1.0"
authors = ["emil"]
edition = "2018"

[dependencies]
ascii = "0.5.0"
chrono = "0.2.25"
derive_more = "0.99.8"
getopts = "0.2.19"
handlebars = "0.15.0"
rand = "0.3.13"
regex = "0.1"
rustc-serialize = "0.3.24"
tiny_http = "0.5"
