[package]
name = "hermes"
version = "0.1.0"
authors = ["emil"]
edition = "2018"

[dependencies]
rand = "0.3.13"
chrono = "0.2.25"
tiny_http = "0.5"
rustc-serialize = "0.3.24"
ascii = "0.5.0"
handlebars = "0.15.0"
regex = "0.1"
getopts = "0.2.19"
